### ISSUE TITLE
Initial Feedback & Issues

### ISSUE THREAD

**Issue by calebjacob** [near/boilerplate-template-js#7]
Great work putting this template together! It works well and looks great. After using the template, I have a few suggestions and ran into a few issues:

### Issues

**1.** After running through the build and start commands, the application works in the browser. However, running `npm test` eventually times out with an error (no code changes were made):

<img width="1036" alt="Screen Shot 2023-01-19 at 11 59 49 AM" src="https://user-images.githubusercontent.com/1475067/213535663-8bd03388-efaf-4825-bf12-9dc11776da2e.png">

**2.** When running `npm run dev` (to run Next JS in hot reload dev mode), the CONTRACT_NAME env variable isn’t correctly passed in to the application.

This command in frontend/package.json:

`"dev": "next dev",`

Needs to change to:

`"dev": "dotenv -c -e ../contract/neardev/dev-account.env -- next dev",`

### README Suggestions

**1.** "Use this template and start to build your own gallery project!" => This should probably read: “to build your own project!” (remove the word “gallery”). As a dev, I'm using this template to build my own project - not a gallery project.

**2.** Should mention option to use nvm to set correct Node/NPM version based on `.nvmrc` file in getting started section: `nvm use`

**3.** `create-near-app` is missing the consistent formatting (needs wrapping backticks) in the "Built With" section.

**4.** “Build your contract” under "Getting Started" isn’t totally accurate. The `npm run build` command builds your contract and the Next JS app - so maybe this step should be labeled “Build your contract and Next JS app:”

It also wouldn’t hurt to document all of these commands:

```
"start": "cd frontend && npm run start",
"dev": "cd frontend && npm run dev",
"deploy": "cd contract && npm run deploy",
"build": "npm run build:contract && npm run build:frontend",
"build:frontend": "cd frontend && npm run build",
"build:contract": "cd contract && npm run build",
```

Most developers will want to build the contract and then run `npm run dev` to work on the frontend with hot reloading - the build/start commands won’t hot reload. Might want to consider documenting these commands for getting started instead:

```
npm run build:contract
npm run deploy
npm run dev
```

**5.** The formatting for “Deploy, Step 1” isn’t quite right. The `near login` and `near create-account ...` commands should be formatted with backticks to render as codeblocks.

**6.** After “Deploy, Step 3”, you should tell the user that they will need to rebuild/restart the Next JS app to pick up the CONTRACT_NAME change - regardless if using `npm run dev` or `npm run build/start`

**7.** Really nit picky: Should have consistent capitalization on deploy step titles.

`Step 1: Create an account for the contract` compared to `Step 2: deploy the contract` - change to: (Step 2: Deploy…), (Step 3: Set…)

**Comment by jon-lewis** [comment]
> Needs to change to:
>
> `"dev": "dotenv -c -e ../contract/neardev/dev-account.env -- next dev",`

I suggest we stop using `dotenv`. We can just use the built-in NextJS tooling.

I created a PR here: https://github.com/near/boilerplate-template-js/pull/8

**Comment by jon-lewis** [comment]
> However, running npm test eventually times out with an error

Unfortunately, it doesn't seem like `near-workspaces-js` works with node 18. Try using node 16 to run the tests @calebjacob.

CC @shelegdmitriy 

PR: https://github.com/near/boilerplate-template-js/pull/10
